//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GICCustomerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMyhcl
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string Band { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public string Location { get; set; }
        public Nullable<int> TotalLeaves { get; set; }
        public string email { get; set; }
    }
}
