//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GICCustomerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserEmailID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CustomerId { get; set; }
    
        public virtual CompanyID CompanyID { get; set; }
    }
}
