//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonolithicWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_Transactions
    {
        public int TnsactionID { get; set; }
        public System.DateTime AppliedDate { get; set; }
        public string LeaveType { get; set; }
        public int EmpID { get; set; }
        public System.DateTime LeaveOnDate { get; set; }
        public string Status { get; set; }
    }
}
